name: Run Moderator Picker

on:
  schedule:
    - cron: '0 9 * * 1-5'  # JSTの18:00 → UTCの9:00、平日（月～金）
  workflow_dispatch:       # 手動実行も可能

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode Google Credentials (復号)
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_B64 }}" | base64 -d > google_calendar_credentials.json

      - name: Run bot script
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MEMBER_IDS: ${{ secrets.MEMBER_IDS }}
          GOOGLE_APPLICATION_CREDENTIALS: google_calendar_credentials.json
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python choose_moderator.py
